# Site settings
title: "Adrian (Sin Acento) Ayala"
description: Hago café y guiones para cómic.

author: Adrian Ayala
email: adrian.ayala17@gmail.com
twitter_username: adrrian17
github_username: adrrian17

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adrianayala.mx" # the base hostname & protocol for your site
http-url: "http://adrianayala.mx"

google_analytics_id: UA-40108887-6
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:day/:title

sass:
  style: compressed

exclude: [vendor]
